#!/bin/sh

url=$(cat /tmp/spotify_metadata.txt | sed -n '2p')
trackid=$(cat /tmp/spotify_metadata.txt | sed -n '3p')
title=$(cat /tmp/spotify_metadata.txt | sed -n '4p')
artist=$(cat /tmp/spotify_metadata.txt | sed -n '5p')
album=$(cat /tmp/spotify_metadata.txt | sed -n '6p')
art=$(cat /tmp/spotify_metadata.txt | sed -n '7p')

if [[ -n "$trackid" ]]; then
    echo "(label :xalign 0.5 :text '  $title - $artist')"
fi
