#!/usr/bin/env bash

pushd /mnt/home/ezequiel/.dotfiles || exit

nix-shell -p nixUnstable git --run "
    git add . &&
    nix flake update --impure .#ramis &&
    nixos-install --impure --root /mnt --flake .#ramis
"

popd || exit