#!/usr/bin/env bash

parted -a opt -s /dev/sda \
    mklabel gpt \
    mkpart primary 512MiB 100% \
    mkpart ESP fat32 1MiB 512MiB \
    set 2 esp on \

mkfs.ext4 -L nixos /dev/sda1
mkfs.fat -F 32 -n boot /dev/sda2

mount /dev/disk/by-label/nixos /mnt
mkdir -p /mnt/boot
mount /dev/disk/by-label/boot /mnt/boot

parted /dev/sda print

mkdir -p /mnt/home/ezequiel
mv /home/nixos/.dotfiles /mnt/home/ezequiel/
cd /mnt/home/ezequiel
