#!/usr/bin/env bash

pushd /mnt/home/ezequiel/.dotfiles || exit

rm -f flake.lock
git add .

nix-shell -p nixUnstable --run "nixos-install --verbose --no-root-passwd --root /mnt --flake .#ramis"

popd || exit
